const VERSION="0.1.1";
const state={route:"home",filter:"All",completed:Number(localStorage.getItem("ns_completed")||0),messages:[["ai","I’m your NorthStar companion. Ask about a concept, lab, or learning path."]],selectedLab:0};
const curriculum=[
["01","Security Foundations","Networking, Linux, identity and core security concepts","12 lessons","Foundation"],
["02","Network Security","TCP/IP, segmentation, protocols, firewalls and traffic analysis","16 lessons","Network"],
["03","Systems & Cloud","Operating systems, cloud architecture and hardening","14 lessons","Foundation"],
["04","Defensive Security","Detection engineering, logs, SIEM and incident response","18 lessons","Defensive"],
["05","Offensive Security","Web, API, application and adversary simulation fundamentals","20 lessons","Offensive"],
["06","Security Engineering","Automation, secure development and security architecture","15 lessons","Foundation"]];
const labs=[
["Packet Recon","Analyze a controlled packet capture","Beginner","Inspect packets, identify protocols, and document observations."],
["Web Surface","Map a deliberately vulnerable web surface","Intermediate","Enumerate an intentionally isolated application and record its attack surface."],
["Detection Drill","Turn telemetry into a detection rule","Intermediate","Inspect simulated telemetry and produce a defensible detection hypothesis."],
["Incident Room","Triage a simulated security incident","Advanced","Build a timeline from controlled evidence and document containment decisions."]];
const nav=[["home","Home","⌂"],["learn","Learn","▤"],["labs","Labs","⌁"],["ai","AI","✦"],["progress","Progress","◉"]];
const esc=s=>s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const go=r=>{state.route=r;render()};
function render(){
 const app=document.querySelector("#app");
 app.innerHTML='<main class="shell"><header class="top"><div class="brand"><span class="mark">N</span><span>NorthStar</span></div><span class="eyebrow">v'+VERSION+'</span></header><div id="view"></div><nav class="nav">'+nav.map(n=>'<button class="'+(state.route===n[0]?"active":"")+'" data-route="'+n[0]+'"><span style="font-size:19px;line-height:18px">'+n[2]+'</span>'+n[1]+'</button>').join("")+'</nav></main>';
 document.querySelector("#view").innerHTML=(views[state.route]||views.home)();bind();
}
const views={
home:()=>'<section class="fade"><div class="hero glass"><span class="eyebrow">Capability platform</span><h1 class="title">Your capability.<br>Your path.<br>Your evidence.</h1><p class="subtitle">A structured cybersecurity environment for learning, practicing, and proving real-world capability.</p><div class="grid stats"><div class="card glass stat"><b>42%</b><span>Path complete</span></div><div class="card glass stat"><b>04</b><span>Labs ready</span></div><div class="card glass stat"><b>'+state.completed+'</b><span>Lessons done</span></div></div></div><div class="section"><div class="section-head"><h2>Continue learning</h2><button class="action" data-route="learn">View path</button></div><button class="card glass lesson" data-route="lesson" style="width:100%;text-align:left"><div class="icon">02</div><div class="lesson-main"><strong>Network Security</strong><small>TCP/IP · traffic · segmentation</small><div class="progress"><i></i></div></div><b>42%</b></button></div><div class="section grid two"><div class="card glass"><span class="eyebrow">Next action</span><h2>Complete your first packet analysis</h2><p class="subtitle">Move from theory to observable evidence in a controlled lab.</p><button class="chip active" data-route="labs" style="margin-top:14px">Open Labs →</button></div><div class="card glass"><span class="eyebrow">Capability snapshot</span><div class="skill"><span>Networking</span><b>42%</b></div><div class="skill"><span>Linux</span><b>28%</b></div><div class="skill"><span>Detection</span><b>12%</b></div></div></div></section>',
learn:()=>{
 const filtered=state.filter==="All"?curriculum:curriculum.filter(c=>c[4]===state.filter);
 return '<section class="fade"><span class="eyebrow">Curriculum</span><h1 class="title">Build the stack.</h1><p class="subtitle">Progress from foundations to security engineering without hiding the hard parts.</p><div class="tabs">'+["All","Foundation","Network","Defensive","Offensive"].map(x=>'<button class="chip '+(state.filter===x?"active":"")+'" data-filter="'+x+'">'+x+'</button>').join("")+'</div><div class="list">'+(filtered.length?filtered.map(c=>'<button class="card glass school" data-route="lesson" style="width:100%;text-align:left"><div class="icon">'+c[0]+'</div><div><strong>'+c[1]+'</strong><p>'+c[2]+'</p></div><span class="badge">'+c[3]+'</span></button>').join(""):'<div class="empty card glass">No curriculum items match this filter.</div>')+'</div><div class="section card glass"><span class="eyebrow">Lesson engine</span><h2>TCP/IP Foundations</h2><p class="subtitle">Read → Practice → Check. Completion is stored locally on this device.</p><button class="chip active" data-complete style="margin-top:12px">'+(state.completed?"Complete another lesson":"Mark lesson complete")+'</button></div></section>';
},
lesson:()=>'<section class="fade"><button class="back" data-route="learn">← Back to curriculum</button><div class="card glass"><span class="eyebrow">Lesson 01 · Network Security</span><h1 class="title" style="font-size:36px">TCP/IP Foundations</h1><p class="subtitle">Understand how hosts communicate, where protocols sit in the stack, and why defenders care about traffic boundaries.</p><div class="section"><div class="tabs"><span class="chip active">Read</span><span class="chip">Practice</span><span class="chip">Check</span></div><h2>What to understand</h2><p class="subtitle">The TCP/IP model gives you a practical mental model for interpreting packets and network telemetry. Focus on addressing, transport behavior, ports, and the difference between a connection and an application protocol.</p><div class="card" style="background:#f8fafc;margin-top:14px"><strong>Evidence checkpoint</strong><p class="subtitle">Explain the TCP three-way handshake in your own words before moving to the packet lab.</p></div><button class="chip active" data-complete style="margin-top:14px">Mark complete</button></div></div></section>',
labs:()=>'<section class="fade"><span class="eyebrow">Practice environment</span><h1 class="title">Labs that leave evidence.</h1><p class="subtitle">Controlled exercises designed to turn concepts into observable skills.</p><div class="list section">'+labs.map((l,i)=>'<article class="card glass lesson lab"><div class="icon">0'+(i+1)+'</div><div class="lesson-main"><strong>'+l[0]+'</strong><small>'+l[1]+'</small></div><button class="badge" data-lab="'+i+'">Start</button></article>').join("")+'</div><div class="section card glass"><span class="eyebrow">Lab status</span><h2>Execution layer</h2><p class="subtitle">The UI is ready for a future sandbox/runner. No fake execution is presented as real.</p></div></section>',
lab:()=>{const l=labs[state.selectedLab];return '<section class="fade"><button class="back" data-route="labs">← Back to labs</button><div class="card glass"><span class="eyebrow">Controlled lab</span><h1 class="title" style="font-size:36px">'+l[0]+'</h1><p class="subtitle">'+l[1]+'.</p><div class="section card" style="background:#f8fafc"><span class="badge">'+l[2]+'</span><h2>Objective</h2><p class="subtitle">'+l[3]+'</p><h2>Runner status</h2><p class="subtitle">Not connected. This phase validates the interface and workflow only.</p></div><button class="chip active" data-route="labs">Return to labs</button></div></section>'},
ai:()=>'<section class="fade"><span class="eyebrow">AI companion</span><h1 class="title">Think with the system.</h1><p class="subtitle">Use the companion to explain, challenge, and connect what you are learning.</p><div class="section card glass chat"><div class="messages">'+state.messages.map(m=>'<div class="msg '+(m[0]==="user"?"user":"")+'">'+esc(m[1])+'</div>').join("")+'</div><form class="composer" id="chat"><input id="prompt" autocomplete="off" placeholder="Ask: explain TCP three-way handshake"><button class="send">Send</button></form></div></section>',
progress:()=>'<section class="fade"><span class="eyebrow">Progress</span><h1 class="title">See the evidence.</h1><div class="section grid two"><div class="card glass" style="display:grid;place-items:center"><div class="ring"><span>42%</span></div><h2 style="margin-bottom:0">Capability path</h2><p class="subtitle" style="text-align:center">Keep building across knowledge, practice and evidence.</p></div><div class="card glass"><span class="eyebrow">Skill matrix</span>'+[["Networking",42],["Linux",28],["Web Security",18],["Detection",12],["Automation",8]].map(s=>'<div class="skill"><span>'+s[0]+'</span><div class="meter"><i style="width:'+s[1]+'%"></i></div></div>').join("")+'</div></div></section>'
};
function bind(){
 document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>go(b.dataset.route));
 document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});
 document.querySelectorAll("[data-lab]").forEach(b=>b.onclick=()=>{state.selectedLab=Number(b.dataset.lab);state.route="lab";render()});
 const c=document.querySelector("[data-complete]");
 if(c)c.onclick=()=>{state.completed++;localStorage.setItem("ns_completed",state.completed);render()};
 const f=document.querySelector("#chat");
 if(f)f.onsubmit=e=>{e.preventDefault();const i=document.querySelector("#prompt"),q=i.value.trim();if(!q)return;state.messages.push(["user",q],["ai","For this UI phase, the companion is a local interaction shell. A real model connection will be added only when the backend contract is defined."]);render()};
}
render();