FROM diegosouzapw/omniroute:latest

ENV NODE_ENV=production \
    PORT=20128 \
    HOSTNAME=0.0.0.0 \
    DATA_DIR=/app/data \
    REQUIRE_API_KEY=true \
    AUTH_COOKIE_SECURE=true

VOLUME ["/app/data"]
EXPOSE 20128
